# bat is a better cat
brew "bat"
# chezmoi for dotfile management
brew "chezmoi"
# direnv to manage environment variables locally
brew "direnv"
# fd for easier filename searching
brew "fd"
# fzf for fuzzy file selection
brew "fzf"
# fzy for fuzzy file selection (that matches GitHub)
brew "fzy"
# git to get the latest
brew "git"
# python no longer included with macOS
brew "python3"
# ripgrep for searching
brew "ripgrep"
# scmpuff enhances some git commands
brew "scmpuff"
# zoxide for quick directory switching
brew "zoxide"

# rocket for easy emoji typing outside of Slack
cask "rocket"
